**Seq2Seq 번역기 예제(Character Embedding)**

![Seq2Seq](Seq2Seq.png)

![Seq2Seq_Decoder](Seq2Seq_2.png)

In [58]:
import os
import shutil
import zipfile

import pandas as pd
import tensorflow as tf
import urllib3
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

**eng-france 언어 parallel corpus 파일 다운로드**

In [59]:
import requests

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

def download_zip(url, output_path):
    response = requests.get(url, headers=headers, stream=True)
    if response.status_code == 200:
        with open(output_path, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)
        print(f"ZIP file downloaded to {output_path}")
    else:
        print(f"Failed to download. HTTP Response Code: {response.status_code}")

url = "http://www.manythings.org/anki/fra-eng.zip"
output_path = "fra-eng.zip"
download_zip(url, output_path)

path = os.getcwd()
zipfilename = os.path.join(path, output_path)

with zipfile.ZipFile(zipfilename, 'r') as zip_ref:
    zip_ref.extractall(path)

ZIP file downloaded to fra-eng.zip

In [82]:
lines = pd.read_csv('kor.txt', names=['src', 'tar', 'lic'], sep='\t')
del lines['lic']
print('전체 샘플의 개수 :',len(lines))

전체 샘플의 개수 : 10

In [83]:
lines = lines.loc[:, 'src':'tar']
lines = lines[0:10] # 10개만 저장
lines.sample(10)

     src    tar
0    Go.    가 !
5  Fire!  불이야 !
3   Who?   누구 ?
9  Stop!   멈춰 !
1    Hi.   안녕 !
2   Run!   달려 !
4   Wow!  대단해 !
6  Help!  도와줘 !
8  Jump!    뛰어.
7  Hide.    숨어.

**Decoder Input에 시작을 의미하는 <sos>를 추가해 줌. 여기서는 <sos>대신 \t 로 표시**

In [84]:
lines.tar = lines.tar.apply(lambda x : '\t '+ x + ' \n')
lines.sample(10)

     src          tar
7  Hide.    \t 숨어. \n
5  Fire!  \t 불이야 ! \n
2   Run!   \t 달려 ! \n
4   Wow!  \t 대단해 ! \n
6  Help!  \t 도와줘 ! \n
1    Hi.   \t 안녕 ! \n
0    Go.    \t 가 ! \n
9  Stop!   \t 멈춰 ! \n
8  Jump!    \t 뛰어. \n
3   Who?   \t 누구 ? \n

**Character 단위 token으로 학습하기 때문에 문자 집합 구축**

In [85]:
# 문자 집합 구축
src_vocab = set()
for line in lines.src: # 1줄씩 읽음
    for char in line: # 1개의 문자씩 읽음
        src_vocab.add(char)

tar_vocab = set()
for line in lines.tar:
    for char in line:
        tar_vocab.add(char)

In [89]:
tar_vocab

['\t',
 '\n',
 ' ',
 '!',
 '.',
 '?',
 '\u202f',
 '가',
 '구',
 '녕',
 '누',
 '단',
 '달',
 '대',
 '도',
 '뛰',
 '려',
 '멈',
 '불',
 '숨',
 '안',
 '야',
 '어',
 '와',
 '이',
 '줘',
 '춰',
 '해']

In [90]:
src_vocab_size = len(src_vocab)+1
tar_vocab_size = len(tar_vocab)+1
print('source 문장의 char 집합 :',src_vocab_size)
print('target 문장의 char 집합 :',tar_vocab_size)

source 문장의 char 집합 : 24
target 문장의 char 집합 : 29

In [91]:
src_vocab = sorted(list(src_vocab))
tar_vocab = sorted(list(tar_vocab))
print(src_vocab[:10])
print(tar_vocab[:10])

['!', '.', '?', 'F', 'G', 'H', 'J', 'R', 'S', 'W']
['\t', '\n', ' ', '!', '.', '?', '\u202f', '가', '구', '녕']

**각 문자에 인덱스 부여**

In [92]:
src_to_index = dict([(word, i+1) for i, word in enumerate(src_vocab)])
tar_to_index = dict([(word, i+1) for i, word in enumerate(tar_vocab)])
print(src_to_index)
print(tar_to_index)

{'!': 1, '.': 2, '?': 3, 'F': 4, 'G': 5, 'H': 6, 'J': 7, 'R': 8, 'S': 9, 'W': 10, 'd': 11, 'e': 12, 'h': 13, 'i': 14, 'l': 15, 'm': 16, 'n': 17, 'o': 18, 'p': 19, 'r': 20, 't': 21, 'u': 22, 'w': 23}
{'\t': 1, '\n': 2, ' ': 3, '!': 4, '.': 5, '?': 6, '\u202f': 7, '가': 8, '구': 9, '녕': 10, '누': 11, '단': 12, '달': 13, '대': 14, '도': 15, '뛰': 16, '려': 17, '멈': 18, '불': 19, '숨': 20, '안': 21, '야': 22, '어': 23, '와': 24, '이': 25, '줘': 26, '춰': 27, '해': 28}

**Source 문장의 글자를 숫자로 인코딩**

In [93]:
encoder_input = []

# 1개의 문장
for line in lines.src:
  encoded_line = []
  # 각 줄에서 1개의 char
  for char in line:
    # 각 char을 정수로 변환
    encoded_line.append(src_to_index[char])
  encoder_input.append(encoded_line)
print('source 문장의 정수 인코딩 :',encoder_input[:5])

source 문장의 정수 인코딩 : [[5, 18, 2], [6, 14, 2], [8, 22, 17, 1], [10, 13, 18, 3], [10, 18, 23, 1]]

**Target 문장의 글자를 정수 인코딩, Decoder Input으로 (SOS) 포함**

In [94]:
decoder_input = []
for line in lines.tar:
  encoded_line = []
  for char in line:
    encoded_line.append(tar_to_index[char])
  decoder_input.append(encoded_line)
print('target 문장의 정수 인코딩 :',decoder_input[:5])

target 문장의 정수 인코딩 : [[1, 3, 8, 3, 4, 3, 2], [1, 3, 21, 10, 3, 4, 3, 2], [1, 3, 13, 17, 3, 4, 3, 2], [1, 3, 11, 9, 3, 6, 3, 2], [1, 3, 14, 12, 28, 7, 4, 3, 2]]

**Target 문장 레이블의 정수 인코딩, Decoder Output으로 (SOS) 미포함, 그림 참조**

In [95]:
decoder_target = []
for line in lines.tar:
  timestep = 0
  encoded_line = []
  for char in line:
    if timestep > 0:
      encoded_line.append(tar_to_index[char])
    timestep = timestep + 1
  decoder_target.append(encoded_line)
print('target 문장 레이블의 정수 인코딩 :',decoder_target[:5])

target 문장 레이블의 정수 인코딩 : [[3, 8, 3, 4, 3, 2], [3, 21, 10, 3, 4, 3, 2], [3, 13, 17, 3, 4, 3, 2], [3, 11, 9, 3, 6, 3, 2], [3, 14, 12, 28, 7, 4, 3, 2]]

In [96]:
max_src_len = max([len(line) for line in lines.src])
max_tar_len = max([len(line) for line in lines.tar])
print('source 문장의 최대 길이 :',max_src_len)
print('target 문장의 최대 길이 :',max_tar_len)

source 문장의 최대 길이 : 5
target 문장의 최대 길이 : 9

**샘플들의 길이를 가장 긴 문장에 맞춤**

In [97]:
encoder_input = pad_sequences(encoder_input, maxlen=max_src_len, padding='post')
decoder_input = pad_sequences(decoder_input, maxlen=max_tar_len, padding='post')
decoder_target = pad_sequences(decoder_target, maxlen=max_tar_len, padding='post')

**모든 값에 대해서 원-핫 인코딩 수행**

In [98]:
encoder_input = to_categorical(encoder_input)
decoder_input = to_categorical(decoder_input)
decoder_target = to_categorical(decoder_target)

In [99]:
from tensorflow.keras.layers import Input, LSTM, Embedding, Dense
from tensorflow.keras.models import Model
import numpy as np

**LSTM 은닉상태 크기는 256, 인코더읠 내부 상태를 디코더로 넘겨 주기 위해 return_state=True**

In [100]:
encoder_inputs = Input(shape=(None, src_vocab_size))
encoder_lstm = LSTM(units=256, return_state=True)

# encoder_outputs은 여기서는 불필요
encoder_outputs, state_h, state_c = encoder_lstm(encoder_inputs)

# LSTM은 바닐라 RNN과는 달리 상태가 두 개. 은닉 상태와 셀 상태.
encoder_states = [state_h, state_c]

**디코더는 인코더의 마지막 은닉 상태를 initial_state로 사용.<br>encoder_inputs과 decoder_inputs를 받아서 decoder_outputs 이 나오도록 학습.**

In [101]:
decoder_inputs = Input(shape=(None, tar_vocab_size))
decoder_lstm = LSTM(units=256, return_sequences=True, return_state=True)

# 디코더에게 인코더의 은닉 상태, 셀 상태를 전달.
decoder_outputs, _, _= decoder_lstm(decoder_inputs, initial_state=encoder_states)

decoder_softmax_layer = Dense(tar_vocab_size, activation='softmax')
decoder_outputs = decoder_softmax_layer(decoder_outputs)

model = Model([encoder_inputs, decoder_inputs], decoder_outputs)
model.compile(optimizer="rmsprop", loss="categorical_crossentropy")

In [102]:
from tensorflow.keras.models import load_model
model.fit(x=[encoder_input, decoder_input], y=decoder_target, batch_size=5, epochs=400, validation_split=0.2)
#model=load_model('my_model.keras')

Epoch 1/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 6s 523ms/step - loss: 3.3525 - val_loss: 3.2783
Epoch 2/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - loss: 3.2537 - val_loss: 3.1734
Epoch 3/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 3.1037 - val_loss: 2.8694
Epoch 4/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step - loss: 2.6890 - val_loss: 2.2423
Epoch 5/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - loss: 2.2748 - val_loss: 2.1411
Epoch 6/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 2.2051 - val_loss: 2.1234
Epoch 7/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 2.0975 - val_loss: 2.2016
Epoch 8/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - loss: 2.0316 - val_loss: 2.0376
Epoch 9/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - loss: 1.9928 - val_loss: 1.9955
Epoch 10/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 1.9755 - val_loss: 1.9843
Epoch 11/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - loss: 1.9553 - val_loss: 1.9695
Epoch 12/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - loss: 2.1015 - val_loss: 1.9766
Epoch 13/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - loss: 1.8731 - val_loss: 2.1446
Epoch 14/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - loss: 1.8241 - val_loss: 2.1064
Epoch 15/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 1.7893 - val_loss: 2.4393
Epoch 16/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - loss: 1.9379 - val_loss: 2.3540
Epoch 17/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - loss: 1.8417 - val_loss: 2.2137
Epoch 18/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - loss: 1.8138 - val_loss: 2.5003
Epoch 19/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 1.8645 - val_loss: 2.1073
Epoch 20/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - loss: 1.7018 - val_loss: 2.0639
Epoch 21/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - loss: 1.6651 - val_loss: 2.0120
Epoch 22/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - loss: 1.7043 - val_loss: 1.9103
Epoch 23/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - loss: 1.8591 - val_loss: 1.9604
Epoch 24/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - loss: 1.6235 - val_loss: 2.3200
Epoch 25/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - loss: 1.6733 - val_loss: 2.2442
Epoch 26/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - loss: 1.6196 - val_loss: 2.1887
Epoch 27/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - loss: 1.6571 - val_loss: 2.6531
Epoch 28/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - loss: 1.7597 - val_loss: 1.9636
Epoch 29/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - loss: 1.5607 - val_loss: 2.0681
Epoch 30/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 1.5259 - val_loss: 1.9210
Epoch 31/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - loss: 1.5906 - val_loss: 1.8771
Epoch 32/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - loss: 1.7516 - val_loss: 1.9081
Epoch 33/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 1.5220 - val_loss: 2.0627
Epoch 34/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - loss: 1.4639 - val_loss: 1.9248
Epoch 35/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - loss: 1.5250 - val_loss: 1.8811
Epoch 36/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - loss: 1.7179 - val_loss: 1.8799
Epoch 37/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 1.4718 - val_loss: 1.9937
Epoch 38/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - loss: 1.3941 - val_loss: 2.0469
Epoch 39/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - loss: 1.3633 - val_loss: 2.0611
Epoch 40/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - loss: 1.3355 - val_loss: 2.3466
Epoch 41/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - loss: 1.5420 - val_loss: 2.6416
Epoch 42/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - loss: 1.4944 - val_loss: 1.9190
Epoch 43/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 1.3347 - val_loss: 2.3273
Epoch 44/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - loss: 1.4338 - val_loss: 2.3313
Epoch 45/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - loss: 1.4906 - val_loss: 2.4383
Epoch 46/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - loss: 1.4288 - val_loss: 2.1265
Epoch 47/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 1.2735 - val_loss: 2.1198
Epoch 48/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - loss: 1.2514 - val_loss: 2.2480
Epoch 49/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - loss: 1.3167 - val_loss: 2.6391
Epoch 50/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 1.4551 - val_loss: 2.0404
Epoch 51/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step - loss: 1.2083 - val_loss: 2.1329
Epoch 52/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - loss: 1.1832 - val_loss: 2.0831
Epoch 53/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - loss: 1.1553 - val_loss: 2.3611
Epoch 54/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - loss: 1.3092 - val_loss: 2.7491
Epoch 55/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 1.4369 - val_loss: 2.0589
Epoch 56/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - loss: 1.0960 - val_loss: 1.8937
Epoch 57/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 1.0797 - val_loss: 1.9316
Epoch 58/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - loss: 1.0563 - val_loss: 1.8399
Epoch 59/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 1.0733 - val_loss: 1.8510
Epoch 60/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 1.0261 - val_loss: 1.8785
Epoch 61/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 1.0517 - val_loss: 1.7998
Epoch 62/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - loss: 1.2869 - val_loss: 1.8050
Epoch 63/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - loss: 1.1482 - val_loss: 1.9097
Epoch 64/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - loss: 0.9187 - val_loss: 1.9411
Epoch 65/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 0.8892 - val_loss: 1.9574
Epoch 66/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - loss: 0.8543 - val_loss: 2.1705
Epoch 67/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 0.8328 - val_loss: 2.0475
Epoch 68/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 0.8010 - val_loss: 2.1419
Epoch 69/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 0.7927 - val_loss: 2.3686
Epoch 70/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - loss: 0.8099 - val_loss: 3.3300
Epoch 71/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - loss: 1.4964 - val_loss: 2.1002
Epoch 72/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - loss: 0.7710 - val_loss: 2.2772
Epoch 73/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - loss: 0.7332 - val_loss: 2.1435
Epoch 74/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - loss: 0.6675 - val_loss: 2.0326
Epoch 75/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.6335 - val_loss: 2.1371
Epoch 76/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - loss: 0.5975 - val_loss: 2.1537
Epoch 77/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - loss: 0.5760 - val_loss: 2.2103
Epoch 78/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step - loss: 0.5464 - val_loss: 2.2437
Epoch 79/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 0.5153 - val_loss: 2.3464
Epoch 80/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 0.5857 - val_loss: 3.7919
Epoch 81/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 1.3461 - val_loss: 2.1846
Epoch 82/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - loss: 0.5031 - val_loss: 2.0369
Epoch 83/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.4500 - val_loss: 2.1374
Epoch 84/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - loss: 0.4252 - val_loss: 2.1300
Epoch 85/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - loss: 0.3980 - val_loss: 2.2567
Epoch 86/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - loss: 0.3764 - val_loss: 2.1127
Epoch 87/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - loss: 0.3615 - val_loss: 2.2978
Epoch 88/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - loss: 0.3463 - val_loss: 2.4828
Epoch 89/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 0.3482 - val_loss: 2.3220
Epoch 90/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.3725 - val_loss: 2.5075
Epoch 91/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - loss: 0.3279 - val_loss: 2.3063
Epoch 92/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - loss: 0.3008 - val_loss: 2.3201
Epoch 93/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - loss: 0.3266 - val_loss: 2.2469
Epoch 94/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - loss: 0.4009 - val_loss: 2.2477
Epoch 95/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - loss: 0.3933 - val_loss: 2.2886
Epoch 96/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 255ms/step - loss: 0.2464 - val_loss: 2.4022
Epoch 97/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - loss: 0.2167 - val_loss: 2.4484
Epoch 98/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - loss: 0.2108 - val_loss: 2.5649
Epoch 99/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - loss: 0.2054 - val_loss: 2.5583
Epoch 100/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - loss: 0.1848 - val_loss: 2.5385
Epoch 101/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - loss: 0.1758 - val_loss: 2.4155
Epoch 102/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 0.1782 - val_loss: 2.6051
Epoch 103/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - loss: 0.1535 - val_loss: 2.3998
Epoch 104/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 0.1537 - val_loss: 2.5160
Epoch 105/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - loss: 0.1581 - val_loss: 2.8025
Epoch 106/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - loss: 0.1482 - val_loss: 3.1267
Epoch 107/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - loss: 0.4841 - val_loss: 4.3762
Epoch 108/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - loss: 0.7155 - val_loss: 2.3179
Epoch 109/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - loss: 0.2164 - val_loss: 2.7152
Epoch 110/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - loss: 0.1740 - val_loss: 2.4561
Epoch 111/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - loss: 0.1408 - val_loss: 2.4666
Epoch 112/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - loss: 0.1063 - val_loss: 2.5382
Epoch 113/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - loss: 0.1032 - val_loss: 2.5576
Epoch 114/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - loss: 0.0955 - val_loss: 2.5474
Epoch 115/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - loss: 0.0922 - val_loss: 2.6581
Epoch 116/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - loss: 0.0873 - val_loss: 2.6638
Epoch 117/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - loss: 0.0791 - val_loss: 2.6884
Epoch 118/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - loss: 0.0743 - val_loss: 2.7208
Epoch 119/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 0.0708 - val_loss: 2.6697
Epoch 120/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - loss: 0.0696 - val_loss: 2.8215
Epoch 121/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - loss: 0.0709 - val_loss: 2.7835
Epoch 122/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - loss: 0.0595 - val_loss: 2.8408
Epoch 123/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - loss: 0.0564 - val_loss: 2.8151
Epoch 124/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - loss: 0.0531 - val_loss: 2.9282
Epoch 125/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - loss: 0.0486 - val_loss: 2.8676
Epoch 126/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0480 - val_loss: 2.9460
Epoch 127/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - loss: 0.0441 - val_loss: 2.9252
Epoch 128/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - loss: 0.0410 - val_loss: 3.0854
Epoch 129/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - loss: 0.0392 - val_loss: 2.8318
Epoch 130/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - loss: 0.0416 - val_loss: 3.2018
Epoch 131/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 0.0533 - val_loss: 2.8891
Epoch 132/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - loss: 0.0432 - val_loss: 3.2574
Epoch 133/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - loss: 0.0335 - val_loss: 3.1553
Epoch 134/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - loss: 0.0282 - val_loss: 3.1258
Epoch 135/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 0.0261 - val_loss: 3.0577
Epoch 136/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - loss: 0.0256 - val_loss: 3.1171
Epoch 137/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 0.0234 - val_loss: 3.1837
Epoch 138/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - loss: 0.0224 - val_loss: 3.2028
Epoch 139/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - loss: 0.0209 - val_loss: 3.2445
Epoch 140/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - loss: 0.0196 - val_loss: 3.2081
Epoch 141/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - loss: 0.0197 - val_loss: 3.3206
Epoch 142/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - loss: 0.0214 - val_loss: 3.7571
Epoch 143/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - loss: 0.6875 - val_loss: 4.6171
Epoch 144/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 1.2046 - val_loss: 2.8301
Epoch 145/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 0.0417 - val_loss: 2.8694
Epoch 146/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - loss: 0.0322 - val_loss: 2.9024
Epoch 147/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - loss: 0.0280 - val_loss: 2.9485
Epoch 148/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - loss: 0.0252 - val_loss: 2.9849
Epoch 149/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - loss: 0.0233 - val_loss: 3.0038
Epoch 150/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - loss: 0.0218 - val_loss: 3.0352
Epoch 151/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - loss: 0.0207 - val_loss: 3.0665
Epoch 152/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - loss: 0.0197 - val_loss: 3.0853
Epoch 153/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 0.0188 - val_loss: 3.1034
Epoch 154/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - loss: 0.0179 - val_loss: 3.1239
Epoch 155/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - loss: 0.0172 - val_loss: 3.1505
Epoch 156/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - loss: 0.0165 - val_loss: 3.1778
Epoch 157/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - loss: 0.0160 - val_loss: 3.1753
Epoch 158/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - loss: 0.0153 - val_loss: 3.2094
Epoch 159/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - loss: 0.0149 - val_loss: 3.2483
Epoch 160/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - loss: 0.0142 - val_loss: 3.2501
Epoch 161/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - loss: 0.0138 - val_loss: 3.2743
Epoch 162/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - loss: 0.0134 - val_loss: 3.2981
Epoch 163/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - loss: 0.0130 - val_loss: 3.3074
Epoch 164/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - loss: 0.0123 - val_loss: 3.3065
Epoch 165/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - loss: 0.0118 - val_loss: 3.3196
Epoch 166/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step - loss: 0.0113 - val_loss: 3.3351
Epoch 167/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 288ms/step - loss: 0.0110 - val_loss: 3.3052
Epoch 168/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 229ms/step - loss: 0.0106 - val_loss: 3.3594
Epoch 169/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - loss: 0.0103 - val_loss: 3.3884
Epoch 170/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 211ms/step - loss: 0.0099 - val_loss: 3.4061
Epoch 171/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - loss: 0.0096 - val_loss: 3.4216
Epoch 172/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - loss: 0.0093 - val_loss: 3.4369
Epoch 173/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - loss: 0.0089 - val_loss: 3.4256
Epoch 174/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - loss: 0.0086 - val_loss: 3.4667
Epoch 175/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - loss: 0.0083 - val_loss: 3.4753
Epoch 176/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - loss: 0.0080 - val_loss: 3.4129
Epoch 177/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - loss: 0.0078 - val_loss: 3.4265
Epoch 178/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - loss: 0.0075 - val_loss: 3.4492
Epoch 179/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 0.0072 - val_loss: 3.4931
Epoch 180/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - loss: 0.0068 - val_loss: 3.4911
Epoch 181/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 0.0067 - val_loss: 3.4740
Epoch 182/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 0.0065 - val_loss: 3.5692
Epoch 183/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 0.0062 - val_loss: 3.5408
Epoch 184/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - loss: 0.0060 - val_loss: 3.5625
Epoch 185/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 0.0058 - val_loss: 3.5858
Epoch 186/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - loss: 0.0056 - val_loss: 3.5165
Epoch 187/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - loss: 0.0055 - val_loss: 3.5892
Epoch 188/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - loss: 0.0052 - val_loss: 3.5619
Epoch 189/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - loss: 0.0051 - val_loss: 3.5840
Epoch 190/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - loss: 0.0049 - val_loss: 3.6231
Epoch 191/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - loss: 0.0048 - val_loss: 3.6261
Epoch 192/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - loss: 0.0046 - val_loss: 3.6283
Epoch 193/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - loss: 0.0045 - val_loss: 3.6154
Epoch 194/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step - loss: 0.0044 - val_loss: 3.7046
Epoch 195/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - loss: 0.0043 - val_loss: 3.6910
Epoch 196/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - loss: 0.0042 - val_loss: 3.6535
Epoch 197/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 275ms/step - loss: 0.0040 - val_loss: 3.6799
Epoch 198/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step - loss: 0.0039 - val_loss: 3.7352
Epoch 199/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step - loss: 0.0039 - val_loss: 3.6636
Epoch 200/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - loss: 0.0038 - val_loss: 3.6988
Epoch 201/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - loss: 0.0036 - val_loss: 3.7111
Epoch 202/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - loss: 0.0036 - val_loss: 3.7238
Epoch 203/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - loss: 0.0035 - val_loss: 3.7576
Epoch 204/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - loss: 0.0034 - val_loss: 3.7220
Epoch 205/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - loss: 0.0033 - val_loss: 3.7693
Epoch 206/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - loss: 0.0032 - val_loss: 3.8072
Epoch 207/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - loss: 0.0032 - val_loss: 3.8147
Epoch 208/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - loss: 0.0031 - val_loss: 3.8247
Epoch 209/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - loss: 0.0030 - val_loss: 3.8125
Epoch 210/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - loss: 0.0030 - val_loss: 3.8237
Epoch 211/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - loss: 0.0029 - val_loss: 3.8172
Epoch 212/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 0.0028 - val_loss: 3.8008
Epoch 213/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - loss: 0.0028 - val_loss: 3.8336
Epoch 214/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - loss: 0.0027 - val_loss: 3.8334
Epoch 215/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - loss: 0.0027 - val_loss: 3.8248
Epoch 216/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - loss: 0.0026 - val_loss: 3.8842
Epoch 217/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - loss: 0.0026 - val_loss: 3.8280
Epoch 218/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 0.0025 - val_loss: 3.8868
Epoch 219/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - loss: 0.0025 - val_loss: 3.8696
Epoch 220/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - loss: 0.0024 - val_loss: 3.8653
Epoch 221/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 0.0024 - val_loss: 3.9133
Epoch 222/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - loss: 0.0024 - val_loss: 3.9252
Epoch 223/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - loss: 0.0023 - val_loss: 3.8961
Epoch 224/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - loss: 0.0023 - val_loss: 3.9076
Epoch 225/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - loss: 0.0022 - val_loss: 3.9219
Epoch 226/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - loss: 0.0022 - val_loss: 3.9197
Epoch 227/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 0.0022 - val_loss: 3.9456
Epoch 228/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 0.0021 - val_loss: 3.9528
Epoch 229/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - loss: 0.0021 - val_loss: 3.9254
Epoch 230/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 0.0021 - val_loss: 3.9610
Epoch 231/400
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 0.0020 - val_loss: 3.9698
Epoch 232/400

**인코더 정의. encoder_inpus와 encoder_states는 훈련 과정에서 정의한 것 재사용<br>1. 번역하고자 하는 입력 문장이 인코더에 들어가서 은닉 상태와 셀 상태를 얻습니다.<br>2. 상태와 <SOS>에 해당하는 \t를 디코더로 보냅니다.<br>3. 디코더가 <EOS>에 해당하는 \n이 나올 때까지 다음 문자를 예측하는 행동을 반복합니다.**

In [103]:
encoder_model = Model(inputs=encoder_inputs, outputs=encoder_states)

In [104]:
# 이전 시점의 상태들을 저장하는 텐서
decoder_state_input_h = Input(shape=(256,))
decoder_state_input_c = Input(shape=(256,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]

# 문장의 다음 단어를 예측하기 위해서 초기 상태(initial_state)를 이전 시점의 상태로 사용.
# 뒤의 함수 decode_sequence()에 동작을 구현 예정
decoder_outputs, state_h, state_c = decoder_lstm(decoder_inputs, initial_state=decoder_states_inputs)

# 훈련 과정에서와 달리 LSTM의 리턴하는 은닉 상태와 셀 상태를 버리지 않음.
decoder_states = [state_h, state_c]
decoder_outputs = decoder_softmax_layer(decoder_outputs)
decoder_model = Model(inputs=[decoder_inputs] + decoder_states_inputs, outputs=[decoder_outputs] + decoder_states)

In [105]:
index_to_src = dict((i, char) for char, i in src_to_index.items())
index_to_tar = dict((i, char) for char, i in tar_to_index.items())

In [106]:
def decode_sequence(input_seq):
  # 입력으로부터 인코더의 상태를 얻음
  states_value = encoder_model.predict(input_seq)

  # <SOS>에 해당하는 원-핫 벡터 생성
  target_seq = np.zeros((1, 1, tar_vocab_size))
  target_seq[0, 0, tar_to_index['\t']] = 1.

  stop_condition = False
  decoded_sentence = ""

  # stop_condition이 True가 될 때까지 루프 반복
  while not stop_condition:
    # 이전 시점의 상태 states_value를 현 시점의 초기 상태로 사용
    output_tokens, h, c = decoder_model.predict([target_seq] + states_value)

    # 예측 결과를 문자로 변환
    sampled_token_index = np.argmax(output_tokens[0, -1, :])
    sampled_char = index_to_tar[sampled_token_index]

    # 현재 시점의 예측 문자를 예측 문장에 추가
    decoded_sentence += sampled_char

    # <eos>에 도달하거나 최대 길이를 넘으면 중단.
    if (sampled_char == '\n' or
        len(decoded_sentence) > max_tar_len):
        stop_condition = True

    # 현재 시점의 예측 결과를 다음 시점의 입력으로 사용하기 위해 저장
    target_seq = np.zeros((1, 1, tar_vocab_size))
    target_seq[0, 0, sampled_token_index] = 1.

    # 현재 시점의 상태를 다음 시점의 상태로 사용하기 위해 저장
    states_value = [h, c]

  return decoded_sentence

In [107]:
for seq_index in [3,2,1,7]: # 입력 문장의 인덱스
  input_seq = encoder_input[seq_index:seq_index+1]
  decoded_sentence = decode_sequence(input_seq)
  print(35 * "-")
  print('입력 문장:', lines.src[seq_index])
  print('정답 문장:', lines.tar[seq_index][2:len(lines.tar[seq_index])-1]) # '\t'와 '\n'을 빼고 출력
  print('번역 문장:', decoded_sentence[1:len(decoded_sentence)-1]) # '\n'을 빼고 출력

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 542ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 383ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step
-----------------------------------
입력 문장: Who?
정답 문장: 누구 ?
번역 문장: 누구 ?
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
-----------------------------------
입력 문장: Run!
정답 문장: 달려 !
번역 문장: 달려 !
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step
-----------------------------------
입력 문장: Hi.
정답 문장: 안녕 !
번역 문장: 안녕 !
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
-----------------------------------
입력 문장: Hide.
정답 문장: 숨어.
번역 문장: 숨어.